---

- name: Setup git config
  hosts: all
  tasks:
    - name: "Include secrets from encrypted_vars.yml"
      include_vars:
        file:
          ../secrets/encrypted_vars.yml
      no_log: true

    - name: Set git name using secrets
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"

    - name: Set git email using secrets
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
