---

- name: Add emacs copr repo
  hosts: all
  become: true
  tasks:
    - name: Enable emacs copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: bhavin192/emacs-pretest
        chroot: fedora-38-x86_64
